name: quantecon
channels:
  - default
dependencies:
  - python=3.10
# - julia=1.9
# - anaconda=2023.03
  - pip
  - pip:
    - jupyter-book==0.15.1
    - quantecon-book-theme==0.4.1
    - sphinx-tojupyter==0.3.0
    - sphinxext-rediraffe==0.2.7
    - sphinx-exercise==0.4.1
    - ghp-import==2.1.0
    - sphinxcontrib-youtube==1.2.0
    - sphinx-togglebutton==0.3.2
    - arviz==0.13.0
    - kaleido
    - matplotlib==3.7.1
    - numba==0.57.1
    - quantecon==0.7.1
    - pandas==2.0.2
    - pandas-datareader==0.10.0
    - yfinance==0.2.22